/*
 * Copyright (c) 2007-2018, Marketo, Inc. All rights reserved.
 * See https://developers.marketo.com/MunchkinLicense.pdf for license terms
 * Marketo marketing automation web activity tracking script
 * Version: 156 r739
 */
 (function(k){if(!k.MunchkinTracker){var l=k.document,n=l.location,A=encodeURIComponent,x=null,B=[],s=function(b,a,d,c){try{var g=function(){try{d.apply(this,arguments)}catch(a){}};b.addEventListener?b.addEventListener(a,g,c||!1):b.attachEvent&&b.attachEvent("on"+a,g);B.push([b,a,g,c])}catch(e){}},P=function(b,a,d,c){try{b.removeEventListener?b.removeEventListener(a,d,c||!1):b.detachEvent&&b.detachEvent("on"+a,d)}catch(g){}},e=function(b){return"undefined"!==typeof b&&null!==b},C=function(b,a){return b.className.match(RegExp("(\\s|^)"+
a+"(\\s|$)"))},Q=e(k.XMLHttpRequest)&&e((new k.XMLHttpRequest).withCredentials),r=function(b){var a=null,d;if(e(b))if(0===b.length)a="";else try{a=decodeURIComponent(b)}catch(c){d=b.indexOf("?");if(-1!==d)try{a=decodeURIComponent(b.substr(0,d))+b.substr(d)}catch(g){}e(a)||(a=String(b))}return a},D=function(b,a){var d={},c=e(a)?a:"=",g=b.split("&"),h=g.length,f,m,l;for(f=0;f<h;f+=1)m=g[f].split(c),e(m)&&1<m.length&&(l=m.shift(),m=m.join(c),d[r(l)]=r(m));return d},E=function(b){try{var a=l.createElement("a");
a.href=b;return D(a.search.substr(1))}catch(d){return null}},F=function(b,a){var d=null,c=[];if(e(b))for(d in b)b.hasOwnProperty(d)&&"function"!==typeof b[d]&&null!==b[d]&&c.push(A(d)+(e(a)?a:"=")+A(b[d]));return c.join("&")},G=function(b,a){var d=null;if(e(a)&&e(b))for(d in b)b.hasOwnProperty(d)&&e(a[d])&&(b[d]=a[d])},K=function(b,a,d){var c=b.split("."),g=c.length,h=2;if(e(a))h=a;else if(e(d)&&d)"com"!==c[g-1]&&(a=RegExp("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"),
4===g&&a.test(b)?h=4:2===c[g-1].length&&1<g&&"co"===c[g-2]&&(h=3));else if(2<c[g-1].length)h=2;else if(2===c[g-1].length)h=3;else return b;for(;c.length>h&&2<c.length;)c.shift();return c.join(".")},u=function(b){var a=l.cookie,d,c,g={id:null,token:null};b=A(b);g.store=function(a,c,d,g){var e=b+"="+F(this,":"),f=new Date;0<a?f.setTime(f.getTime()+864E5*a):f.setTime(f.getTime()-1);e+="; expires="+f.toGMTString();c&&(e+="; path="+c);d&&-1!==d.indexOf(".")&&(e+="; domain="+d);g&&(e+="; secure");l.cookie=
e};if(""!==a)for(a=a.split(";"),d=0;d<a.length;d+=1)if(c=a[d].replace(/^\s+|\s+$/g,""),0===c.indexOf(b+"=")){a=c.substring(b.length+1);d=D(a);e(d.id)&&e(d.token)?G(g,d):G(g,D(a,":"));break}return g},f={customName:null,notifyPrefix:null,wsInfo:null,altIds:[],visitorToken:null,cookieLifeDays:730,clickTime:350,cookieAnon:!0,mkt_tok:null,domainLevel:null,domainSelectorV2:!1,replayDetectLimit:5E3,httpsOnly:!1,asyncOnly:!1,anonymizeIP:!1,apiOnly:!1,externalSource:null,_mcid:null,orgId:null},v=null,p=null,
R=k.navigator.cookieEnabled||l.hasOwnProperty("cookie")&&(0<l.cookie.length||-1<(l.cookie="testcookie=test; max-age=10000").indexOf.call(l.cookie,"testcookie=test;")),y=!1,z=[],H=null,S=function(b,a,d){var c=new k.XMLHttpRequest;c.open("GET",b,!0!==a);c.onreadystatechange=function(){2<=c.readyState&&c.abort()};if(a)try{c.timeout=d}catch(e){}try{c.send()}catch(f){}},L=function(b,a,d,c,e){b=b+a+"&"+F(d)+"&"+F(c);d=(new Date).getTime();e=!e&&!f.asyncOnly;0===a.indexOf("webevents/visitWebPage?")&&(e=
!1);Q?S(b,e,f.clickTime):(new k.Image(1,1)).src=b;H=d+f.clickTime},T=function(){var b;return function(a,d){var c={x:a.clientX,y:a.clientY,el:d,time:(new Date).getTime()};if(e(b)&&c.x===b.x&&c.y===b.y&&c.el===b.el&&c.time<b.time+f.replayDetectLimit)return!0;b=c;return!1}}(),M=function(){var b=l.getElementsByName("_mkt_trk"),a=0,d="";e(p)&&(d="id:"+p.id+"&token:"+p.token);for(a=0;a<b.length;a+=1)"hidden"===b[a].type&&(b[a].value=d)},t=function(b,a,d,c){var g=null,h;h=n.hostname;var l=n.protocol,m="webevents/"+
b;if(y){var k;if(k=window.navigator)a:{k=window.navigator.userAgent;if("string"===typeof k&&k){if(0<=k.indexOf("AdsBot")||0<=k.indexOf("Wget")||0<=k.indexOf("msnbot")){k=!0;break a}if(0<=k.indexOf("Mozilla")&&(0<=k.indexOf("slurp")||0<=k.indexOf("bot"))){k=!0;break a}}k=!1}if(!k&&e(p)&&(a._mchId=p.id,a._mchTk=p.token,e(f.mkt_tok)&&(a.mkt_tok=f.mkt_tok),e(f.wsInfo)&&(a._mchWs=f.wsInfo),"clickLink"===b&&(a._mchCn=e(f.customName)?f.customName:""),a._mchHo=h,a._mchPo=n.port,e(a._mchRu)||(a._mchRu=r(n.pathname)),
a._mchPc=l,a._mchVr="156",e(h)&&0!==h.length&&"file:"!==l))for(g in f.anonymizeIP&&(a.aip=1),e(f.externalSource)&&(a._mchEs=f.externalSource),e(x)&&(a._mchEcid=x),m+="?_mchNc="+(new Date).getTime(),L(f.notifyPrefix,m,a,d,c),f.altIds)f.altIds.hasOwnProperty(g)&&(h=f.altIds[g],a._mchId=h,L(f.notifyPrefix.replace(/\w{3}\-\w{3}\-\w{3}\.mktoresp\.com/i,h+".mktoresp.com"),m,a,d,c))}else z.push(["post",arguments])},N=function(b){var a=b||k.event,d=a.target||a.srcElement,c={},g;g=a.which;var f=a.button;g=
e(g)&&(1===g||2===g)||e(f)&&(0===f||1===f||4===f)?!0:!1;if(g&&!a._mchDone){a._mchDone=!0;a=d;g=n.href||n;for(-1<g.indexOf("#")&&(g=g.substring(0,g.indexOf("#")));"A"!==a.tagName&&"AREA"!==a.tagName&&e(a.parentNode);)a=a.parentNode;a===l||a===k||"A"!==a.tagName&&"AREA"!==a.tagName?a=null:(d=a.href.replace(/^\s+|\s+$/g,""),a=e(d)&&0<d.length&&0!==d.indexOf("#")&&0!==d.indexOf(g+"#")&&0!==d.indexOf("javascript")&&0!==d.indexOf("mailto")&&!C(a,"mchNoDecorate")?a:null);e(a)&&!T(b,a)&&(c._mchHr=r(a.href),
t("clickLink",c))}},w=function(b){if(y){if(null!==p)return p;var a=K(n.hostname,f.domainLevel,f.domainSelectorV2),d=u("_mkto_trk"),c=!1!==f.httpsOnly;if(e(d.id)||f.cookieAnon||b){if(d.id=v,e(d.token)||(e(f.visitorToken)&&"VISITOR_MKTTOK_REPLACE"!==f.visitorToken?d.token=f.visitorToken:d.token="_mch-"+a+"-"+(new Date).getTime()+"-"+(Math.floor(9E4*Math.random())+1E4)),d.store(f.cookieLifeDays,"/",a,c),c&&(d=u("_mkto_trk")),!c||e(d.id))return p=d,M(),d}else return null}else z.push(["createTrackingCookie",
arguments])},O=function(){w(!0)},U=function(b){var a=b.onclick;b.onclick="function"===typeof a?function(){O.apply(b,arguments);return a.apply(b,arguments)}:O},I=function(b){var a=K(n.hostname,f.domainLevel,f.domainSelectorV2),d=u("mkto_opt_out"),c=!1!==f.httpsOnly;b?(d.id=!0,d.store(730,"/",a,c),b=u("_mkto_trk"),b.id&&b.store(0,"/",a,c)):d.store(0,"/",a,c)},V=function(b){if(!e(b))return null;9<b.length&&b.indexOf("@AdobeOrg",b.length-9)===b.length-9&&(b=b.substring(0,b.length-9));if(e(window.Visitor))try{var a=
window.Visitor.getInstance(b);if(e(a))return a.getMarketingCloudVisitorID()}catch(d){}var c,f;return null!==(c=RegExp("AMCV_"+b+"%40AdobeOrg=([^;]+)").exec(l.cookie))&&null!==(f=/MCMID%7C([0-9]+)/.exec(c[1]))?f[1]:null},J={ASSOCIATE_LEAD:"associateLead",CLICK_LINK:"clickLink",VISIT_WEB_PAGE:"visitWebPage",init:function(b,a){if(R&&e(b)&&0!==b.length){v=b;v=v.toUpperCase();var d="",c,g,h;c=E(k.location.toString());var q=null;f.notifyPrefix=n.protocol+"//"+v+".mktoresp.com/";e(a)&&(window.console.debug('Munchkin.init("%s") options:',
b,a),G(f,a));e(c)&&(e(c.mkt_tok)&&(f.mkt_tok=c.mkt_tok),e(c.lpview)&&(d=c.lpview),e(c.marketo_opt_out)&&(q=c.marketo_opt_out));if(!e(f.mkt_tok))if(c=E(l.referrer),e(c.mkt_tok))f.mkt_tok=c.mkt_tok;else if(e(c.enid)&&e(c.type))for(h in c)c.hasOwnProperty(h)&&"enid"!==h&&"type"!==h&&(-1<h.indexOf("mkt_tok")||-1<c[h].indexOf("mkt_tok"))&&(g=E(h+"="+c[h]),e(g.mkt_tok)&&(f.mkt_tok=g.mkt_tok));if("preview"!==d||!/\/lpeditor\/preview$/.test(n.pathname)){if(null===q){if(d=u("mkto_opt_out"),e(d.id)){I(!0);
return}}else{if("true"===q){I(!0);return}"false"===q&&I(!1)}if(!y){y=!0;d=w(e(f.mkt_tok));q={};for(c={};0<z.length;)switch(h=z.shift(),h[0]){case "createTrackingCookie":d=w.apply(l,h[1]);break;case "post":t.apply(l,h[1])}e(f._mcid)?x=f._mcid:e(f.orgId)&&(x=V(f.orgId));if(e(d))f.apiOnly||(q._mchCn=e(f.customName)?f.customName:"",c._mchHa=r(n.hash),c._mchRe=r(l.referrer),c._mchQp=r(n.search.substr(1).replace(/&/g,"__-__")),t("visitWebPage",q,c,!0));else if(!(f.cookieAnon||e(k.Mkto)&&e(k.Mkto.formSubmit))){d=
[];h=l.forms;var q=h.length,m,p;for(c=0;c<q;c+=1)if(C(h[c],"lpeRegForm"))for(m=h[c].elements,p=m.length,g=0;g<p;g+=1)"submit"!==m[g].type||C(m[g],"mchNoDecorate")||d.push(m[g]);for(h=0;h<d.length;h+=1)U(d[h])}}}}},munchkinFunction:function(b,a,d){var c={},f={},h=null;e(d)&&(c._mchKy=d);switch(b){case "associateLead":for(h in a)a.hasOwnProperty(h)&&(c["_mchAt"+h]=a[h]);w(!0);t("associateLead",c);break;case "clickLink":e(a.href)&&(c._mchHr=c._mchLr=a.href,t("clickLink",c));break;case "visitWebPage":e(a.url)&&
(c._mchRu=a.url),e(a.params)&&(c._mchQp=a.params),e(a.name)&&(c._mchCn=a.name),f._mchRe=n.href,t("visitWebPage",c,f)}},createTrackingCookie:function(b){w(b)}};Date.prototype.getTimeAlias=Date.prototype.getTime;s(k,"beforeunload",function(){for(var b;0<B.length;)b=B.shift(),P.apply(this,b);if(e(H)){do b=new Date;while(b.getTimeAlias()<H)}});s(l,"click",N,!0);(function(b){var a=!1,d=!0,c=l.documentElement,e=function(c){"readystatechange"===c.type&&"complete"!==l.readyState||a||(a=!0,b.call(k,c.type||
c))},f=null,f=function(){try{c.doScroll("left")}catch(a){k.setTimeout(f,50);return}e("poll")};if("complete"===l.readyState)b.call(k,"lazy");else{if(l.createEventObject&&c.doScroll){try{d=!k.frameElement}catch(n){}d&&f()}s(l,"DOMContentLoaded",e);s(l,"readystatechange",e);s(k,"load",e)}})(function(){M();var b=0;if(e(l.links))for(b=0;b<l.links.length;b+=1)s(l.links[b],"click",N,!0)});k.MunchkinTracker=k.Munchkin=J;k.mktoMunchkin=J.init;k.mktoMunchkinFunction=J.munchkinFunction}})(window);
